# Bybit API (CloudFront) blocks US regions. EU West is required.
[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[deploy.multiRegionConfig.europe-west4-drams3a]
numReplicas = 1
